server:
  port: 8080

spring:
  application:
    name: MY BLOG APPLICATION

  datasource:
    url: jdbc:mysql://localhost:3306/BlogApp
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

